- 
  hosts: all
  become: true
  user: ec2-user
  vars:
    repository: ahmedemad2051
    image_name: jenkins_docker
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: install docker
      yum:
          name: docker
          state: latest
    - name: Start service docker, if not started
      service:
        name: docker
        state: started               
    - name: Creates jenkins_home directory
      file:
          path: /jenkins_home
          state: directory
    - name: build new image jenkins with docker
     docker_image:
       name: {{image_name}}:latest
       repository: {{repository}}/{{image_name}}:latest
       build:
         path: /opt/docker
       source: build        
    - name: create jenkins container
      docker_container:
            name: jenkins-container
            image: {{image_name}}:lts
            user: root
            recreate: yes
            state: started
            volumes:
              - "/jenkins_home:/var/jenkins_home"
              - "/var/run/docker.sock:/var/run/docker.sock"
              - "/usr/bin/docker:/usr/bin/docker"
            ports:
              - "8080:8080"
