- 
  hosts: all
  become: true
  user: ec2-user
  vars:
    repository: ahmedemad2051
    image_name: jenkins_docker
  tasks:
    # - name: upgrade all packages
    #   yum:
    #     name: '*'
    #     state: latest
    # - name: install docker
    #   yum:
    #       name: docker
    #       state: latest
    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker
    # - name: Start service docker, if not started
    #   service:
    #     name: docker
    #     state: started               
    # - name: Creates jenkins_home directory
    #   file:
    #       path: /jenkins_home
    #       state: directory
    - name: Download Dockerfile
      get_url:
        url: https://raw.githubusercontent.com/ahmedemad2051/devops-ITI-challenges/master/challenge-01/ansible/Dockerfile
        dest: /opt/Dockerfile
        mode: '766'
    - name: build new image jenkins with docker
      docker_image:
        name: "{{image_name}}:latest"
        repository: "{{repository}}/{{image_name}}:latest"
        build:
          path: /opt
        source: build        
    - name: create jenkins container
      docker_container:
            name: jenkins-container
            image: "{{image_name}}:lts"
            user: root
            recreate: yes
            state: started
            volumes:
              - "/jenkins_home:/var/jenkins_home"
              - "/var/run/docker.sock:/var/run/docker.sock"
              - "/usr/bin/docker:/usr/bin/docker"
            ports:
              - "8080:8080"
